### ISSUE TITLE
[RU] Feedback for: /_langs/ru/updates/index.html

### ISSUE THREAD

**Issue by Gurylev** [google/WebFundamentals#1334] opened 2015-06-08 14:48 UTC
RSS feed don't work
![RSS feed dont work]
(http://grlv.ru/i/tcfut.png)

**Comment by PaulKinlan** [comment] 2015-06-12 12:41
They shouldnt have been in the output.

**Comment by pbakaus** [comment] 2015-06-16 11:46
This is a duplicate of #1338. These are released tips so they correctly appear in the feed (just not currently on the default sort in the homepage).

**Closed by pbakaus** 2015-06-16 11:46 UTC
