### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en

### ISSUE THREAD

**Issue by davidstoner** [google/WebFundamentals#2404] opened 2016-01-02 07:59 UTC
The timeline tool (as of at least version 47) appears to be largely changed from what the documentation uses as reference. Will the docs be updated soon to explain the new layout?

**Comment by Garbee** [comment] 2016-01-04 15:24
Duplicate of #2349

**Comment by kaycebasques** [comment] 2016-01-11 19:59
You can follow my progress / ask questions / provide feedback on this issue in #2349.

**Closed** 2016-01-11 19:58 UTC
