### ISSUE TITLE
How do you start and stop DevTools

### ISSUE THREAD

**Issue by mrmsbarnes** [google/WebFundamentals#6461] opened 2018-08-04 00:07 UTC
This page
https://developers.google.com/web/tools/chrome-devtools/ or
https://developers.google.com/web/tools/chrome-devtools/#get-started
needs to say how to start and stop DevTools.

I guess it's like walking.  Everyone knows how to walk.  Right?  We can just assume.

**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/#get-started

**What needs to be done?**
Don't bury this in some subsidiary link.  Don't rely on newbies doing unprofitable Google searches.
Say right there on the page,  "You start DevTools in a Chrome tab by hitting F12.  You stop DevTools by hitting F12 again."  I may be wrong.  After all, I'm a newbie.

**Comment by kaycebasques** [comment] 2018-12-15 00:49
Duplicate of #6979 (which is now fixed)

**Closed by kaycebasques** 2018-12-15 00:49 UTC
