### ISSUE TITLE
Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by cronin4392** [google/WebFundamentals#4370] opened 2017-03-29 16:23 UTC
There is a Javascript error on [this page](https://developers.google.com/web/updates/2017/03/chrome-58-deprecations) preventing any other javascript from executing.

**Comment by kosamari** [comment] 2017-07-06 21:14
Hey ya @cronin4392, I was not able to reproduce the error, closing the issue for now but do let us know if you keep seeing the same error.

**Closed by kosamari** 2017-07-06 21:14 UTC
