### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en

### ISSUE THREAD

**Issue by ipoly** [google/WebFundamentals#2412] opened 2016-01-05 15:02 UTC
I find that the timeline panel has updated, it is hard to learn its usage by following this article.

**Comment by Garbee** [comment] 2016-01-08 12:01
Duplicate of #2349

**Closed** 2016-01-11 19:58 UTC

**Comment by kaycebasques** [comment] 2016-01-11 19:59
You can follow my progress / ask questions / provide feedback on this issue in #2349.
