### ISSUE TITLE
[EN] Feedback for: /tools/polymer-starter-kit/index.html

### ISSUE THREAD

**Issue by pauldeden** [google/WebFundamentals#1302] opened 2015-05-29 02:38 UTC
The Polymer Starter Kit download links are broken.

**Comment by arthurvr** [comment] 2015-05-29 04:49
Duplicate of https://github.com/google/WebFundamentals/issues/1298 :)

**Comment by PaulKinlan** [comment] 2015-06-12 12:47
Fixed.

**Closed by PaulKinlan** 2015-06-12 12:47 UTC
