### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by skynet** [google/WebFundamentals#1136] opened 2015-02-11 14:16 UTC
View Source link, front page, top right, is "fundamentally" wrong.

https://developers.google.com/web/fundamentals/

![screenshot_1](https://cloud.githubusercontent.com/assets/139233/6148328/946dff1a-b1ce-11e4-86a7-90f6219684dd.png)

**Comment by arthurvr** [comment] 2015-02-11 14:20
Duplicate of https://github.com/google/WebFundamentals/issues/1132, https://github.com/google/WebFundamentals/issues/1129 and #1133.

**Comment by PaulKinlan** [comment] 2015-02-16 13:30
I believe this has been fixed and is getting ready for deployment.  We've had a fallow few months in terms of updates and we should be sorting that asap.

**Closed** 2015-02-16 13:31 UTC

**Comment by skynet** [comment] 2015-02-16 14:41
:+1:
