### ISSUE TITLE
[EN] Feedback for: /fundamentals/principles/orientation-works-best.html

### ISSUE THREAD

**Issue by usrbowe** [google/WebFundamentals#1549] opened 2015-08-22 19:01 UTC
There is missing "Next Sections" box at the end of this article, as other articles had :+1: 
![keep_menus_short_and_sweet_ _web_fundamentals](https://cloud.githubusercontent.com/assets/5339061/9425440/e21c4102-4910-11e5-8c7c-ccebb3084dcd.jpg)

**Comment by arthurvr** [comment] 2015-08-31 18:58
Dupe of #1327.

**Comment by petele** [comment] 2015-09-09 21:06
I'm going to close this for now since we're just about three weeks from launching the MDL redesign and this will be a moot issue then.

**Closed by petele** 2015-09-09 21:06 UTC
