### ISSUE TITLE
Web Updates: Categories and product categories are missing

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1779] opened 2015-09-22 17:13 UTC
The sidebar at https://developers.google.com/web/updates/ lets you drill down by news type and even more importantly product.

This functionality is needed, as many sub pages such as Chrome DevTools link to certain sub pages, i.e. DevTools-specific tips.

**Comment by petele** [comment] 2015-09-23 14:34
Dupe of #1743

**Closed by petele** 2015-09-23 14:34 UTC
