### ISSUE TITLE
Need way to get subset of updates to be able to include on other pages

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1643] opened 2015-09-11 18:33 UTC
This is needed for /tools - where the included the latest tips and tricks on the home page see https://developers.google.com/web/tools/

**Comment by gauntface** [comment] 2015-09-17 19:29
a.) Do we want to copy this?
b.) If so would page.context.extras work? you could then put anything special in there.

**Comment by gauntface** [comment] 2015-10-27 14:58
Duplicate of #1643.

**Closed by gauntface** 2015-10-27 14:58 UTC
Labels: is-Update, P2, type-Infrastructure
