### ISSUE TITLE
chrome-devtools: where did the Frames mode go?

### ISSUE THREAD

**Issue by mediafreakch** [google/WebFundamentals#2390] opened 2015-12-23 12:45 UTC
I cannot switch to the Frames mode anymore. It's where I used to see and debug the framerate of my web application (vertical bars that were showing if you are above or under 30 / 60 fps). 
I'm using Google Chrome on Mac, Version 47.0.2526.106 (64-bit).

**Comment by Garbee** [comment] 2015-12-30 21:27
The old frames UX was removed. Now there is a single view provided for the Timeline. Frames are now presented as 'FPS' in the current overview area. Trouble frames are marked with a red tick both at the top of that view and on the frame itself.

![new-timeline](https://cloud.githubusercontent.com/assets/868301/12057758/2283bb8c-af12-11e5-9097-37144c445e01.png)

**Comment by mediafreakch** [comment] 2015-12-30 22:24
@garbee Thanks for pointing out what is nowhere really documented! Stupid follow-up question: the lower the bar, the lower the framerate right? And what is the threshold for the red mark; 30 or 60fps?

**Comment by Garbee** [comment] 2015-12-30 23:41
Yes, lower the bar the lower the framerate. As always. That is easily noticed since the framerate mark is over the lower dip. While the higher bars aren't showing any immediate issues.

I think there is some deeper heuristics going on then just a set FPS. I have 2 frames at ~22ms that trigger the flag. However, another at ~24.5ms that isn't triggering it. We'll need to look into it more with the team as it gets documented to tell what is going on.

**Comment by mediafreakch** [comment] 2015-12-31 09:17
> Yes, lower the bar the lower the framerate. As always.

Back in the days with the "Frames" mode it was the other way around. The lower the bar the higher the framerate.

**Comment by Garbee** [comment] 2015-12-31 12:46
As always was more meant as always to how things typically go. ;) Sorry, bad choice of words considering our old UX.

**Comment by Garbee** [comment] 2016-01-08 12:02
This also fits more as a duplicate of #2349.

**Closed** 2016-09-22 22:25 UTC
Labels: section-tools
