### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/?hl=en

### ISSUE THREAD

**Issue by abhijitpai05** [google/WebFundamentals#3099] opened 2016-07-13 14:39 UTC
Not sure if this is the right forum or already there is open item for this, but following page failed to scroll up/down on Safari on Macbook.

https://developers.google.com/web/tools/chrome-devtools/debug/?utm_source=dcc#breakpoints-dynamic-javascript

**Comment by kaycebasques** [comment] 2016-07-13 20:43
Thanks for the feedback @abhijitpai05. Yes, this is the right place for issues if the site is buggy, or if you want to leave feedback on docs content. This issue is a duplicate of #2985.

**Closed by kaycebasques** 2016-07-13 20:43 UTC
