### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en

### ISSUE THREAD

**Issue by riskers** [google/WebFundamentals#2623] opened 2016-03-04 03:57 UTC
omg，today I updated to 49.0 ,Timeline shows :

<img width="609" alt="screenshot 2016-03-04 11 54 56" src="https://cloud.githubusercontent.com/assets/5653652/13517511/1ed2c6e8-e1ff-11e5-9f4b-aa93d65054b9.png">

omg, the doc has not been updated ?

Frankly, look at the document can't completely let me this useless timeline before people understand now how to debug

**Comment by Garbee** [comment] 2016-03-04 16:02
Duplicate of your existing iss #2475.

This is being worked on, but updating the Timeline docs is a major undertaking.

**Comment by kaycebasques** [comment] 2016-03-10 23:01
Hey @riskers, the [doc](https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en) has been updated!

Thanks for your feedback

**Closed by kaycebasques** 2016-03-10 23:01 UTC
Labels: section-tools

**Comment by riskers** [comment] 2016-03-11 03:21
@kaycebasques 

Select `js profile` and `paint` seems to have no effect
