### ISSUE TITLE
[EN] Feedback for: /web/updates/2016/06/css-containment?hl=en

### ISSUE THREAD

**Issue by CNek** [google/WebFundamentals#3081] opened 2016-07-09 07:37 UTC
Can't scroll doc pages properly with Safari 9.1.1 (OS X 10.10.5)
Weird behavior with "ghost jumpy scrolling"

**Comment by cvrebert** [comment] 2016-07-22 17:33
Duplicate of #2985 ?

**Comment by petele** [comment] 2016-09-22 20:44
Fixed.

**Closed by petele** 2016-09-22 20:44 UTC
