### ISSUE TITLE
Overhaul: Title is too big on mobile

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1843] opened 2015-09-24 16:47 UTC
Nexus 5 emulation below:

![image](https://cloud.githubusercontent.com/assets/205226/10079848/048299ae-630a-11e5-884e-320990fafb25.png)

**Comment by petele** [comment] 2015-09-24 16:56
Dupe of #1814

**Closed by petele** 2015-09-24 16:56 UTC
