### ISSUE TITLE
MDL is breaking #urls

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#2291] opened 2015-11-13 02:34 UTC
If we send a user to an anchor in the page it scrolls to the top.  We really need to fix this as every user who is landing from devtools is not seeing the content they needed.

**Comment by gauntface** [comment] 2015-12-01 11:23
I believe this is a MDL 1.0.6 bug - but not sure if our production build is using that yet or not.

**Comment by Garbee** [comment] 2015-12-30 21:38
It is an MDL 1.0 bug period, however it is due to how we handle layout (along with quite a few other problems.) V2 is going to fix it since we will be doing less stuff for developers, thereby avoiding the layout hacks we currently employ.

**Comment by kaycebasques** [comment] 2016-02-02 16:18
Duplicate of #2253

**Comment by sgomes** [comment] 2016-07-19 14:37
Can we have an example URL to reproduce the bug?

**Comment by Garbee** [comment] 2016-07-19 15:29
https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/understanding-resource-timing#diagnosing-network-issues

**Comment by petele** [comment] 2016-07-19 16:19
Yep - I see it happen, page loads at the anchor, then some event fires and the page jumps to the top. If you click on the anchor again, it'll scroll down to that part.

**Comment by petele** [comment] 2016-09-22 22:35
This should be fixed now. Sorry about that!!

**Closed by petele** 2016-09-22 22:35 UTC
