### ISSUE TITLE
[EN] Feedback for: /fundamentals/principles/orientation-works-best.html

### ISSUE THREAD

**Issue by Shaffer319** [google/WebFundamentals#1361] opened 2015-06-12 21:29 UTC
I hit page 3 and there was no navigation at the bottom to continue.
03 Tell users which orientation works best
https://developers.google.com/web/fundamentals/principles/orientation-works-best?hl=en

**Comment by arthurvr** [comment] 2015-08-31 18:58
Dupe of https://github.com/google/WebFundamentals/issues/1327.

**Comment by petele** [comment] 2015-09-09 21:25
I'm going to close this for now as we're working on a complete site refresh using material design lite which should fix this issue.

**Closed by petele** 2015-09-09 21:25 UTC
