### ISSUE TITLE
Feedback for: /fundamentals/resources/styleguide/index.html

### ISSUE THREAD

**Issue by elliottthecreative** [google/WebFundamentals#1133] opened 2015-02-10 19:09 UTC
View source link is broken.

**Comment by PaulKinlan** [comment] 2015-02-10 20:49
This is actually fixed, but not deployed.  It should be soon. Sorry.

**Comment by arthurvr** [comment] 2015-02-10 21:13
Can this issue be closed? It's dupe of https://github.com/google/WebFundamentals/issues/1129 isn't it?

**Closed** 2015-02-16 13:32 UTC
