### ISSUE TITLE
Broken Tools menu link

### ISSUE THREAD

**Issue by Ratchette** [google/WebFundamentals#1739] opened 2015-09-18 00:41 UTC
On the "tools" page ( WebFundamentals home > Tools ) AKA https://developers.google.com/web/tools/?hl=en  clicking on the top menu's "Chrome DevTools" options leads to a 404. 

You are redirected to the address /tools/chrome-devtools whereas it should be /web/tools/chrome-devtools.

It appears to have arisen from commit: d4a3804f4f5817f4169032557baab228ecb5043e

**Comment by gauntface** [comment] 2015-09-18 15:25
@Ratchette I just tried this and everything seems to be working fine.

@petele can you reproduce this bug?

**Comment by vitorinoaraujo** [comment] 2015-09-18 16:09
@gauntface @petele @Ratchette I can reproduce this bug.

Referer: https://developers.google.com/web/tools/?hl=en
Request URL: https://developers.google.com/tools/chrome-devtools
Status Code: 404 OK

**Comment by gauntface** [comment] 2015-09-18 18:26
Got it - thank you.

<img width="1165" alt="google_web_tools" src="https://cloud.githubusercontent.com/assets/139760/9967545/3da2d9ae-5e11-11e5-9940-68649916229b.png">

**Comment by gauntface** [comment] 2015-09-18 18:33
Fixed by: #1746

**Closed by gauntface** 2015-09-18 18:33 UTC
