### ISSUE TITLE
[EN] Feedback for: /web/shows/ttt/series-2/es2015?hl=en

### ISSUE THREAD

**Issue by paullewis** [google/WebFundamentals#2234] opened 2015-10-26 20:27 UTC
If you take videos to full screen they don't show the video.

**Comment by patrickhlauke** [comment] 2015-10-26 20:28
![untitled-2](https://cloud.githubusercontent.com/assets/895831/10741511/128912a6-7c20-11e5-818b-5fbaff5797bb.png)

**Comment by petele** [comment] 2015-10-27 13:58
@gauntface investigated this a bit, and thinks it's an MDL issue.

**Comment by paullewis** [comment] 2015-10-27 14:10
Tagging in @surma and @sgomes... just like #2235 :+1:

**Comment by sgomes** [comment] 2015-10-27 14:27
That's an interesting one, thanks! @gauntface: let me know if you need any help debugging this one.

**Comment by gauntface** [comment] 2015-10-27 14:32
Duplicate of #2189.

I think this is something weird with the layout thing is my guess.

**Closed by gauntface** 2015-10-27 14:32 UTC
Labels: P2, type-Design, type-Infrastructure
