### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by pauldominik** [google/WebFundamentals#2333] opened 2015-12-08 21:51 UTC
Cant view video on full screen.

**Comment by PaulKinlan** [comment] 2015-12-14 07:45
cc @pbakaus

**Comment by Garbee** [comment] 2015-12-30 21:37
Duplicate of issue #2325. 

tldr from comment over there, it is an upstream issue with MDL.

**Comment by kaycebasques** [comment] 2016-02-02 23:15
Please consolidate discussion to #2325

**Closed by kaycebasques** 2016-02-02 23:15 UTC
