### ISSUE TITLE
[EN] Feedback for: /tools/polymer-starter-kit/index.html

### ISSUE THREAD

**Issue by alexramsey92** [google/WebFundamentals#1301] opened 2015-05-29 01:12 UTC
The Polymer starter kit download link leads to a 404 on github.

**Comment by arthurvr** [comment] 2015-05-29 04:49
Duplicate of https://github.com/google/WebFundamentals/issues/1298 :)

**Comment by PaulKinlan** [comment] 2015-06-12 12:47
Fixed.

**Closed by PaulKinlan** 2015-06-12 12:47 UTC
