### ISSUE TITLE
UX for nav menu (new layout) seems unconventional

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#1852] opened 2015-09-24 21:51 UTC
The new nav menu seems unconventional (in terms of UX).

<img width="536" alt="screen shot 2015-09-24 at 2 39 33 pm" src="https://cloud.githubusercontent.com/assets/4713486/10087668/2680183c-62ca-11e5-9523-29b2b940bac5.png">

Clicking on *Showcase* in the screenshot above effectively transports the user to the Showcase section of the site. With *Showcase* in place of *Web Fundamentals* and the top-level Showcase documents listed beneath. 

Pure first impression: As a user I was lost for a couple of seconds. I've never seen a nav UI like this. It took (literally) a couple seconds for me to understand what was going on. 

An accordion-style nav menu seems more conventional to me. 

I *think* the current UI could work, if the site provides a little more visual feedback. Take the screenshot above again for example. When I click on Showcase, some sort of animation that replaces the *Web Fundamentals* link, and then populates the list with the Showcase pages, and then moves *Web Fundamentals* down to the bottom of the nav, would probably be sufficient for me to understand what just happened.

LMK if that all makes sense :+1:

**Comment by petele** [comment] 2015-09-24 21:57
Dupe of #1842. I'm going to close this, but can you please add your comments to #1842 instead? Thanks!!

**Closed by petele** 2015-09-24 21:57 UTC
