### ISSUE TITLE
URL fragment links in deprecations pages don't work when loaded fresh

### ISSUE THREAD

**Issue by davidben** [google/WebFundamentals#2774] opened 2016-04-01 21:11 UTC
If you visit this link:
https://developers.google.com/web/updates/2016/03/chrome-50-deprecations#remove-insecure-tls-version-fallback

It briefly jumps to the right place, but then jumps back to the top. I'm guessing there's some JavaScript on the site that's interfering with the normal behavior.

**Comment by gauntface** [comment] 2016-04-20 09:01
There is Javascript in the page (Material Design Lite). It is a known issue on the project, we are waiting for updates on devsite to fix this. Marking as a duplicate of: https://github.com/google/WebFundamentals/issues/2291

**Closed by gauntface** 2016-04-20 09:01 UTC
