### ISSUE TITLE
[EN] Feedback for: /web/shows/devbytes/?hl=en

### ISSUE THREAD

**Issue by swapy** [google/WebFundamentals#2200] opened 2015-10-21 16:08 UTC
I was watching a youtube video on this site , when i click on fullscreen button of youtube video it looks like this 

![Issue]( http://s15.postimg.org/7wtbxn0m3/Screenshot_from_2015_10_21_21_35_12.png)

**Comment by petele** [comment] 2015-10-21 16:08
Thanks for the feedback, it looks like this is a dupe of #2189

**Closed by petele** 2015-10-21 16:08 UTC
