### ISSUE TITLE
Adjust sizes of heading text

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1814] opened 2015-09-23 14:26 UTC
In general, the h1/2/3/4/5/6 feels too big compared to the rest of the text. It may be that we're just not using the right CSS attributes.

Specific example - see https://material-dot-web-central.appspot.com/web/updates/2015/09/updates-to-cache-api - It feels odd that the page title is smaller than the h2 heading text used on the pages

![screen shot 2015-09-23 at 10 24 35 am](https://cloud.githubusercontent.com/assets/718038/10047705/611b8334-61dd-11e5-86d6-f48fe4dc2984.png)

**Comment by gauntface** [comment] 2015-09-29 16:53
@petele regarding: "It feels odd that the page title is smaller than the h2 heading text used on the pages" do you just want the page title included at the top of the content or is there more / other work to be done here?

**Comment by gauntface** [comment] 2015-09-30 11:18
Discussed offline.

Add title to pages, hide in top bar.

Typography has changed throughout the site - this should be addressed by these changes.

If not - the problem is larger than just updates.

**Closed by gauntface** 2015-09-30 11:18 UTC
Labels: P1, type-Design
