### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/07/interact-with-ble-devices-on-the-web?hl=en

### ISSUE THREAD

**Issue by jyasskin** [google/WebFundamentals#2954] opened 2016-06-03 07:58 UTC
Linking directly to https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web?hl=en#user-gesture-required doesn't scroll to the right place on the page.

**Comment by Garbee** [comment] 2016-06-06 16:03
Duplicate of #2253

**Comment by PaulKinlan** [comment] 2016-07-04 08:54
@sgomes @petele please sort asap, this is getting beyond a joke now.  I know we are planning to migrate back into devsite soon but right now we need to get this fixed, people can't use our site.

**Comment by sgomes** [comment] 2016-07-19 14:34
This is not an MDL issue, as it only affects Web Fundamentals. WF seems to be modifying page and MDL layout styles, and is triggering a Safari bug. Workaround on #3118.

**Closed by sgomes** 2016-07-19 14:34 UTC

**Comment by jyasskin** [comment] 2016-07-19 19:35
I'm using Chrome.

**Comment by sgomes** [comment] 2016-07-26 10:38
Bad dupe, sorry. The follow up to this is on #2291.
