### ISSUE TITLE
[EN] Feedback for: /_langs/en/updates/tools/tip/index.html

### ISSUE THREAD

**Issue by banguit** [google/WebFundamentals#1320] opened 2015-05-31 10:44 UTC
Hi,

When I navigate to the some pages, I see a markup instead of rendered page. Tested in Chrome and Firefox on Mac.

For example:
https://developers.google.com/web/updates/2015/05/19/cycle-through-editing-locations
https://developers.google.com/web/updates/2015/05/19/local-modifications
https://developers.google.com/web/updates/2015/05/19/copy-the-response-of-a-network-resource-to-your-clipboard
https://developers.google.com/web/updates/2015/05/19/reveal-in-elements-panel

Best regards,
Dima

**Comment by PaulKinlan** [comment] 2015-06-04 13:01
It looks like these shouldn't have been deployed yet, or are configured incorrectly.

cc @pbakaus @Meggin

**Comment by petele** [comment] 2015-06-15 20:22
Dupe of #1338 - this was opened first, but the other already has the solution in it.

**Closed by petele** 2015-06-15 20:22 UTC
